### ISSUE TITLE
Cannot execute passkey on iOS device

### ISSUE THREAD

**Issue by edwinius** [duanyytop/capacitor-native-passkey#1]
I got not implemented error on iOS device running iOS 16
using Capacitor 5

[log] - Error on registering PASSKEY {"code":"UNIMPLEMENTED"}
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "WebAuthn.isWebAuthnAvailable()" is not implemented on ios
CapacitorException@http://10.10.20.18:8100/vendor.js:424:10
@http://10.10.20.18:8100/vendor.js:529:41
onInvoke@http://10.10.20.18:8100/vendor.js:111176:31
run@http://10.10.20.18:8100/polyfills.js:8071:41
@http://10.10.20.18:8100/polyfills.js:9150:31
onInvokeTask@http://10.10.20.18:8100/vendor.js:110853:32
onInvokeTask@http://10.10.20.18:8100/vendor.js:111165:35
runTask@http://10.10.20.18:8100/polyfills.js:8117:47
drainMicroTaskQueue@http://10.10.20.18:8100/polyfills.js:8487:30
invokeTask@http://10.10.20.18:8100/polyfills.js:8396:30
invokeTask@http://10.10.20.18:8100/polyfills.js:9519:18
globalCallback@http://10.10.20.18:8100/polyfills.js:9560:33

**Comment by duanyytop** [comment]
I only implemented on Android

**Comment by edwinius** [comment]
> I only implemented on Android

will you be implementing on iOS too?

**Comment by duanyytop** [comment]
Sorry, I have no time now
